### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by yuyedaidao** [AppliKeySolutions/PandoraPlayer#1]
Installing AudioKit (3.7)

[!] Error installing AudioKit
[!] /usr/bin/curl -f -L -o /var/folders/j5/26pxq6rd5v5gljmbhb2szmnc0000gn/T/d20170814-2548-1hkgo2d/file.zip https://github.com/audiokit/AudioKit/releases/download/v3.7/AudioKit.framework.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   612    0   612    0     0    371      0 --:--:--  0:00:01 --:--:--   371
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Operation timed out

**Comment by andfans** [comment]
You can use the Mac App Cocopods.

**Comment by yuyedaidao** [comment]
It still not work
