### ISSUE TITLE
cocopods [!] Unable to find a specification for `PandoraPlayer`

### ISSUE THREAD

**Issue by Xlff** [AppliKeySolutions/PandoraPlayer#2]
ruti

**Comment by AppliKeySolutions** [comment]
We suppose that there is a problem with your pod master repo. Delete and download it again.

You can do:
pod repo remove master
pod setup
pod install

Or:
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install

**Comment by LittleLydia** [comment]
I have done this, but it just always appears!

**Comment by AppliKeySolutions** [comment]
Try: 
pod repo update

Please also check if the platform in your Podfile compatible with the spec's minimum deployment target.
