### ISSUE TITLE
Suggestion: Open Source the Wave Visualization

### ISSUE THREAD

**Issue by gmogames** [AppliKeySolutions/PandoraPlayer#3]
Hi There,

Awesome lib you created, thanks so much. It would be awesome if you could open source/bundle just the waves visualization.

I have an app that uses audio, but we have our own internal player, and I would love to just implement the visual waves while the audio is playing.

Thanks so much once again

**Comment by AppliKeySolutions** [comment]
Hi there,

Please check out these two links:

https://github.com/AppliKeySolutions/PandoraPlayer/blob/master/Player/Classes/Helpers/VisualisationHelper.swift

https://github.com/AppliKeySolutions/PandoraPlayer/blob/master/Player/Classes/Views/WaveVisualizer/WaveVisualizer.swift
