### ISSUE TITLE
not working on xcode 9 

### ISSUE THREAD

**Issue by shaibow** [ApplikeySolutions/PandoraPlayer#6]
Please update podspec file to work with new audiokit and xcode 9

**Comment by AppliKeySolutions** [comment]
Hi, thanks, will take a look soon

**Comment by mohanmoorthy** [comment]
Please update the podspec file

**Comment by haydenholligan** [comment]
How long is soon? It's been 17 days so far since "soon"

**Comment by AppliKey** [comment]
@haydenholligan if you have a free time you can make a pull request with these fixes. Help is much appreciated in open source projects.

**Comment by AppliKey** [comment]
@mohanmoorthy @shaibow 

Hi there,

Please check the new release. Thanks in advance for using our component!

Applikey Team
